#!/usr/bin/env bash
set -euo pipefail

# AWS Lambda custom runtime bootstrap file
# https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
cd "$LAMBDA_TASK_ROOT"
mkdir bin
export PATH=$PWD/bin:$PATH

curl=(curl
  --silent
  --show-error
  --location
)

# [[[cog print('CURL_LATEST_URL=' + github_latest_url('stunnel/static-curl', 'curl-linux-x86_64-8.6.0.tar.xz'))]]]
CURL_LATEST_URL=https://github.com/stunnel/static-curl/releases/download/8.6.0-1/curl-linux-x86_64-8.6.0.tar.xz
# [[[end]]] (checksum: a694e108f548df5d13c8b3c19c698c26)
"${curl[@]}" "$CURL_LATEST_URL" | tar -C bin xvfz -

# [[[cog print('YAJSV_URL=' + github_latest_url('neilpa/yajsv', 'yajsv.linux.amd64'))]]]
YAJSV_URL=https://github.com/neilpa/yajsv/releases/download/v1.4.1/yajsv.linux.amd64
# [[[end]]] (checksum: 2e540365a55197c0547c51598dfdd6c6)
"${curl[@]}" "$YAJSV_URL" -o bin/validate-json-schema
chmod +x bin/validate-json-schema

# Lambda "handler" must be script path relative to directory of `bootstrap`.
# Handler script must include function with name == basename of script file.
SCRIPT_PATH=$_HANDLER
SCRIPT_FN=$(basename "$SCRIPT_PATH" .sh)

curl+=(
  --variable "LAMBDA=http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation"
)

# shellcheck disable=SC1090
source "$(dirname "$0")/$SCRIPT_PATH"

while true
do
  REQUEST_ID_FILE=$(mktemp)
  EVENT_DATA=$(
    "${curl[@]}" \
      --write-out "%output{$REQUEST_ID_FILE}%header{Lambda-Runtime-Aws-Request-Id}" \
      --expand-url "{{LAMBDA}}/next"
  )
  REQUEST_ID=$(cat "$REQUEST_ID_FILE")

  STDOUT_AND_STDERR_LOG=$(mktemp)

  # catch and log errors
  trap 'bootstrap_catch $? $LINENO' ERR
  bootstrap_catch() {
    export retcode=$1
    export lineno=$2
    "${curl[@]}" \
      --expand-url "{{LAMBDA}}/$REQUEST_ID/error" \
      --variable "message@$STDOUT_AND_STDERR_LOG" \
      --variable "script=$SCRIPT_PATH" \
      --variable "%retcode" \
      --variable "%lineno" \
      --expand-variable "trace={{script}}:{{lineno}}" \
      --expand-json '{"errorType":"return code {{retcode}}","errorMessage":{{message:json}},"stacktrace":[{{trace:json}}]}'
  }

  # Execute the handler function from the script
  # https://stackoverflow.com/a/49299040
  {
    "$SCRIPT_FN" "$EVENT_DATA" \
    | tee >(
        # stream stdout (only) to /response
        "${curl[@]}" \
          --expand-url "{{LAMBDA}}/$REQUEST_ID/response" \
          --request POST \
          --data - \
      );
  } 2>&1 \
  | tee "$STDOUT_AND_STDERR_LOG"
done
