
all: $(shell echo \
	board-{fascist-{5or6,7or8,9or10},liberal} \
	player-{fascist,hitler,liberal} \
	policy-{fascist,liberal} \
)

board-fascist-5or6.png:  PAGE=14 
board-fascist-7or8.png:  PAGE=15
board-fascist-9or10.png: PAGE=16
board-liberal.png:       PAGE=17
