#!/usr/bin/env bash
cd "$(dirname "$0")"/.. || exit 1
source scripts/lib/{vars,utils,sms,deck}.bash

while [[ "$RESET" != "RESET" ]]; do
  read -p "To reset game state, please type RESET: " RESET
done
rm -f $SECRET/{policy-{deck,options,discard},player-roles}.txt
rm -f $PUBLIC/policies-enacted.txt
