#!/usr/bin/env bash
cd "$(dirname "$0")"/.. || exit 1
$1/vars.bash
$1/utils.bash
$1/sms.bash
$1/deck.bash

while [[ "$RESET" != "RESET" ]]; do
  read -p "To reset game state, please type RESET: " RESET
done
rm -f $SECRET/{policy-{deck,options,discard},player-roles}.txt
rm -f $PUBLIC/policies-enacted.txt
