#!/usr/bin/env bash
set -euo pipefail

pip-run cogapp -- \
!cog \
  -r `# Replace the input file with the output.` \
  -c `# Checksum the output to protect it against accidental change.` \
  -P `# Use print() instead of cog.outl() for code output.` \
  -p `# Prepend the generator source with PROLOGUE:` \
  "$(printf "%s\n" \
    "import subprocess as sp, re, os, sys, json, pathlib as pl" \
    "from scripts.github_latest import *" \
    "sh = lambda *a,**k: sp.check_output(*a, text=True, **k)" \
  )" \
  "$@"
