#!/usr/bin/env bash
(return 0 2>/dev/null) || cd "$(dirname "$0")"/.. || exit 1
source scripts/__lib.bash

while [[ -z "$CONFIRM" || "$CONFIRM" != "Yes" ]]; do

  read -p "Who is conducting the investigation?    ($PUBLIC_PLAYER_NAMES_PROMPT): " INVESTIGATOR
  read -p "Who is the suspect under investigation? ($PUBLIC_PLAYER_NAMES_PROMPT): " SUSPECT
  echo
  echo "Please confirm:"
  read -p "Who is conducting the investigation?    (confirm): " INVESTIGATOR_CONFIRM
  read -p "Who is the suspect under investigation? (confirm): " SUSPECT_CONFIRM
  echo

  if [[ "$INVESTIGATOR" != "$INVESTIGATOR_CONFIRM" || "$SUSPECT" != "$SUSPECT_CONFIRM" ]]; do
  if []
  read -p "Send $SUSPECT's party membership card to $INVESTIGATOR? (Type \"Yes\" to confirm) "
  echo
done

ensure_drawable_policy_deck

echo -n "Sending $SUSPECT's party membership card to $INVESTIGATOR... "
INVESTIGATOR_PHONE=$(lookup "$PUBLIC_PLAYER_PHONES" "$PUBLIC_PLAYER_NAMES" "$INVESTIGATOR")
INVESTIGATOR_MSG="$INVESTIGATOR, here is $SUSPECT's party membership card."
SUSPECT_PARTYMEM=$(image_url party "$(lookup "`cut -d: -f2 $SECRET/player-roles.txt`" "$PUBLIC_PLAYER_NAMES" "$SUSPECT")")
send_sms "$INVESTIGATOR_PHONE" "$INVESTIGATOR_MSG" "$SUSPECT_PARTYMEM"
echo "Done."
