#!/usr/bin/env bash
(return 0 2>/dev/null) || cd "$(dirname "$0")"/.. || exit 1
source scripts/__lib.bash

while [[ -z "$INVESTIGATOR" || "$INVESTIGATOR" != "$INVESTIGATOR_CONFIRM" ]]; do
  read -p "Who is conducting the investigation? ($PUBLIC_PLAYER_NAMES_PROMPT): " INVESTIGATOR
  read -p "Type again to confirm: " INVESTIGATOR_CONFIRM
done

ensure_drawable_policy_deck

echo -n "Sending preview of top three policies to $INVESTIGATOR... "
INVESTIGATOR_PHONE=$(lookup "$PUBLIC_PLAYER_PHONES" "$PUBLIC_PLAYER_NAMES" "$INVESTIGATOR")
INVESTIGATOR_MSG="$INVESTIGATOR, here are the current top three policies on the policy deck."
INVESTIGATOR_IMG=`image_url policycombo "$(echo -n "$(head -n3 $SECRET/policy-deck.txt)" | tr -d '[[:digit:]]' | tr '\n' '-')"`
send_sms "$INVESTIGATOR_PHONE" "$INVESTIGATOR_MSG" "$INVESTIGATOR_IMG"
echo "Done."
